### ISSUE TITLE
Tracking Pixels On Templates

### ISSUE THREAD

**Issue by johnsiwicki** [bs-production/front-end-guidelines#8]
Potential Fix

``` css
/** Remove 1px image from tracking script **/
img[src*="msn.com"] {
display: none;
}
```
